module JSONP3
  # A JSON Patch containing zero or more patch operations.
  class Patch
    @ops: Array[Op]

    def self.apply!: (Array[Patch::Op | Hash[String, untyped]] ops, untyped value) -> untyped

    # Base class for all JSON Patch operations
    class Op
      # Return the name of the patch operation.
      def name: () -> String

      # Apply the patch operation to _value_.
      def apply!: (untyped _value, Integer _index) -> untyped

      # Return a JSON-like representation of this patch operation.
      def to_h: () -> untyped
    end

    # The JSON Patch _add_ operation.
    class OpAdd < Op
      @pointer: JSONP3::Pointer

      @value: untyped

      # @param pointer [JSONP3::Pointer]
      # @param value [JSON-like value]
      def initialize: (JSONP3::Pointer pointer, untyped value) -> void

      def name: () -> "add"
    end

    # The JSON Patch _remove_ operation.
    class OpRemove < Op
      @pointer: JSONP3::Pointer

      # @param pointer [JSONP3::Pointer]
      def initialize: (JSONP3::Pointer pointer) -> void

      def name: () -> "remove"
    end

    # The JSON Patch _replace_ operation.
    class OpReplace < Op
      @pointer: JSONP3::Pointer

      @value: untyped

      # @param pointer [JSONP3::Pointer]
      # @param value [JSON-like value]
      def initialize: (JSONP3::Pointer pointer, untyped value) -> void

      def name: () -> "replace"
    end

    # The JSON Patch _move_ operation.
    class OpMove < Op
      @from: JSONP3::Pointer

      @pointer: JSONP3::Pointer

      # @param from [JSONP3::Pointer]
      # @param pointer [JSONP3::Pointer]
      def initialize: (JSONP3::Pointer from, JSONP3::Pointer pointer) -> void

      def name: () -> "move"
    end

    # The JSON Patch _copy_ operation.
    class OpCopy < Op
      @from: JSONP3::Pointer

      @pointer: JSONP3::Pointer

      # @param from [JSONP3::Pointer]
      # @param pointer [JSONP3::Pointer]
      def initialize: (JSONP3::Pointer from, JSONP3::Pointer pointer) -> void

      def name: () -> "copy"
              
      def deep_copy: (untyped obj) -> untyped
    end

    # The JSON Patch _test_ operation.
    class OpTest < Op
      @pointer: JSONP3::Pointer

      @value: untyped

      # @param pointer [JSONP3::Pointer]
      # @param value [JSON-like value]
      def initialize: (JSONP3::Pointer pointer, untyped value) -> void

      def name: () -> "test"
    end

    # @param ops [Array<Op>?]
    def initialize: (?Array[Op | Hash[String, untyped]]? ops) -> void

    # @param pointer [String | JSONP3::Pointer]
    # @param value [JSON-like value]
    # @return [self]
    def add: (JSONP3::Pointer | String pointer, untyped value) -> self

    # @param pointer [String | JSONP3::Pointer]
    # @return [self]
    def remove: (JSONP3::Pointer | String pointer) -> self

    # @param pointer [String | JSONP3::Pointer]
    # @param value [JSON-like value]
    # @return [self]
    def replace: (JSONP3::Pointer | String pointer, untyped value) -> self

    # @param from [String | JSONP3::Pointer]
    # @param pointer [String | JSONP3::Pointer]
    # @return [self]
    def move: (JSONP3::Pointer | String from, JSONP3::Pointer | String pointer) -> self

    # @param from [String | JSONP3::Pointer]
    # @param pointer [String | JSONP3::Pointer]
    # @return [self]
    def copy: (JSONP3::Pointer | String from, JSONP3::Pointer | String pointer) -> self

    # @param pointer [String | JSONP3::Pointer]
    # @param value [JSON-like value]
    # @return [self]
    def test: (JSONP3::Pointer | String pointer, untyped value) -> self

    # Apply this patch to JSON-like value _value_.
    def apply!: (untyped value) -> untyped

    def to_a: () -> Array[untyped]

    private

    def ensure_pointer: (JSONP3::Pointer | String pointer, Symbol op, Integer index) -> JSONP3::Pointer
                      
    def build: (Array[Op | Hash[String, untyped]]) -> void
             
    def op_pointer: (Hash[String, untyped] obj, String key, String op, Integer index) -> JSONP3::Pointer

    def op_value: (Hash[String, untyped] obj, String key, String op, Integer index) -> untyped
            
  end
end