module JSONP3
  module Path
    # A compiled JSONPath expression ready to be applied to JSON-like values.
    class Query
      @env: JSONP3::Path::Environment

      @segments: Array[JSONP3::Path::Segment]

      def initialize: (JSONP3::Path::Environment env, Array[JSONP3::Path::Segment] segments) -> void

      def to_s: () -> ::String

      # Apply this JSONPath expression to JSON-like value _root_.
      # @param root [Array, Hash, String, Integer, nil] the root JSON-like value to apply this query to.
      # @return [Array<JSONPathNode>] the sequence of nodes found while applying this query to _root_.
      def find: (untyped root) -> JSONP3::Path::NodeList

      alias apply find

      # Apply this JSONPath expression to JSON-like value _root_.
      # @param root [Array, Hash, String, Integer, nil] the root JSON-like value to apply this query to.
      # @return [Enumerable<JSONPathNode>] the sequence of nodes found while applying this query to _root_.
      def find_enum: (untyped root) ->Enumerable[JSONP3::Path::Node]

      # Return the first node from applying this JSONPath expression to JSON-like value _root_.
      # @param root [Array, Hash, String, Integer, nil] the root JSON-like value to apply this query to.
      # @return [JSONPathNode | nil] the first available node or nil if there were no matches.
      def match: (untyped root) -> (JSONP3::Path::Node | nil)

      # Return `true` if this query results in at least one node, or `false` otherwise.
      # @param root [Array, Hash, String, Integer, nil] the root JSON-like value to apply this query to.
      # @return [bool] `true` if this query results in at least one node, or `false` otherwise.
      def match?: (untyped root) -> bool

      # Return the first node from applying this JSONPath expression to JSON-like value _root_.
      # @param root [Array, Hash, String, Integer, nil] the root JSON-like value to apply this query to.
      # @return [JSONPathNode | nil] the first available node or nil if there were no matches.
      def first: (untyped root) -> (JSONP3::Path::Node | nil)

      # Return _true_ if this JSONPath expression is a singular query.
      def singular?: () -> (false | true)

      # Return _true_ if this JSONPath expression has no segments.
      def empty?: () -> (false | true)
    end
  end
end
